id: A4F4B2188
title: Prayer to Shechen Kongtrul as Vajrasattva
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:35:18.367761
  last_modified_at: 2022-03-01 01:35:18.367767
